# Config file for https://travis-ci.org/

language: php

# Define the php versions against we want to test our code
php:
- 5.6
- 7.0
- 7.1
- 7.2
- 7.3

# Testing the app (see phpunit.xml) for configs, generating Code Coverage report
before_script:
  - wget -nc http://getcomposer.org/composer.phar
  - php composer.phar update

#after_script:

after_success:
# Submit coverage report to https://codecov.io
- bash <(curl -s https://codecov.io/bash)

#after_failure:

# Monitor only these branches
branches:
  only:
  - master

# You can delete the cache using travis-ci web interface
cache:
  directories:
  - $HOME/.composer/cache
